"""Betaflight MCP Server - Configure drones through Claude."""

from .msp import (
    AnalogData,
    Attitude,
    BatteryConfig,
    BlackboxConfig,
    DataflashSummary,
    FailsafeConfig,
    FCInfo,
    FCStatus,
    Features,
    FilterConfig,
    GPSRescueConfig,
    GPSStatus,
    IMUData,
    ModeRange,
    MotorConfig,
    MotorData,
    MSPCode,
    MSPConnection,
    MSPError,
    OSDConfig,
    OSDElement,
    OSDLayout,
    PIDSettings,
    PreflightCheck,
    PreflightResult,
    RCChannels,
    RCTuning,
    RCTuningFull,
    RxFailChannel,
    VTXConfig,
    FEATURE_FLAGS,
    FLIGHT_MODES,
)
try:
    from .server import main
except ImportError:
    main = None  # MCP server not available without mcp package

__all__ = [
    "main",
    "MSPConnection",
    "MSPError",
    "MSPCode",
    "AnalogData",
    "Attitude",
    "BatteryConfig",
    "BlackboxConfig",
    "DataflashSummary",
    "FailsafeConfig",
    "FCInfo",
    "FCStatus",
    "Features",
    "FilterConfig",
    "GPSRescueConfig",
    "GPSStatus",
    "IMUData",
    "ModeRange",
    "MotorConfig",
    "MotorData",
    "OSDConfig",
    "OSDElement",
    "OSDLayout",
    "PIDSettings",
    "PreflightCheck",
    "PreflightResult",
    "RCChannels",
    "RCTuning",
    "RCTuningFull",
    "RxFailChannel",
    "VTXConfig",
    "FEATURE_FLAGS",
    "FLIGHT_MODES",
]
